server:
  port: 8080

grpc:
  client:
      # gRPC的服务端名单@GrpcClient注解中会用到
    mygrpc-server:
      address: 'static://localhost:9091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

